version: '3'
services:
  biosdk_server:
    build: .
    image: bqatsdk-server
    container_name: bqatsdk_server
    ports:
      - "8849:8849"
    environment:
      bqatsdk_zip_url: https://mosip.s3-us-west-2.amazonaws.com/bqatsdk-1.1.0.zip
      bqatsdk_bioapi_impl: io.bqat.sdk.services.impl.BqatQualitySdkService
    restart: always
